// #Stake
export const UPDATE_APY_DETAIL = 'UPDATE_APY_DETAIL';
export const GET_STAKE_APY_DETAIL = 'GET_APY_DETAIL';
export const GET_STAKE_APY_DETAIL_DONE = 'GET_STAKE_APY_DETAIL_DONE';

export const CONFIGURE = 'CONFIGURE'
export const CONFIGURE_RETURNED = 'CONFIGURE_RETURNED'

export const EXIT = 'EXIT'
export const EXIT_RETURNED = 'EXIT_RETURNED'

export const STAKE = 'STAKE'
export const STAKE_RETURNED = 'STAKE_RETURNED'

export const WITHDRAW = 'WITHDRAW'
export const WITHDRAW_RETURNED = 'WITHDRAW_RETURNED'

export const GET_REWARDS = 'GET_REWARDS'
export const GET_REWARDS_RETURNED = 'GET_REWARDS_RETURNED'

export const GET_YCRV_REQUIREMENTS = 'GET_YCRV_REQUIREMENTS'
export const GET_YCRV_REQUIREMENTS_RETURNED = 'GET_YCRV_REQUIREMENTS_RETURNED'

export const GET_GOVERNANCE_REQUIREMENTS = 'GET_GOVERNANCE_REQUIREMENTS'
export const GET_GOVERNANCE_REQUIREMENTS_RETURNED = 'GET_GOVERNANCE_REQUIREMENTS_RETURNED'

export const GET_BALANCES = 'GET_BALANCES'
export const GET_BALANCES_RETURNED = 'GET_BALANCES_RETURNED'

export const ERROR = 'ERROR'