spring:
  application:
    name: eCommerce
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
---

spring:
  server:
    port: 9001
  profiles: development
  datasource:
    url: jdbc:mysql://35.188.35.75/demo
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  server:
    port: 8080
  profiles: production
  datasource:
    url: jdbc:mysql://35.188.35.75/demo
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
