const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const CSSMinimizerPlugin = require("css-minimizer-webpack-plugin");
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const path = require("path");

const devServer = {
	port    : 1234,
	// Index: path.resolve("index.html"),
	// ContentBase: path.resolve("dist"),
	// ContentBasePublicPath: '/demo',
	compress: true,
	hot     : true,
	lazy    : true,
	// UseLocalIp: true,
	// When devServer.lazy is enabled, the dev-server will only compile the bundle when it gets requested.
	// This means that webpack will not watch any file changes. We call this lazy mode.
	https   : true,
	headers : {
		"test-header": "demo-header"
	},
	historyApiFallback: {
		// Index: 'dist/index.html',
		// Rewrites: [
		// 	// { from: /^\/$/, to: '/demo' },
		// 	{ from: /^\/subpage/, to: '/dist/index.html' },
		// 	{ from: /./, to: '/404.html' }
		// ]
	}
};

const resolve = {
	extensions: [
		'.tsx',
		'.ts',
		'.js',
		'.css',
		'.sass',
		'.scss' 
	],
	modules: [ "node_modules" ],
};

const entry = {
	index: "./src/index_r.tsx"
};

const output = {
	path         : path.resolve("dist"),
	chunkFilename: '[name].js',
	filename     : "js/[name].[contenthash:8].js",
};

const plugins = [
	new HtmlWebpackPlugin({
		chunks  : [ "notSupported" ],
		filename: `index.html`,
		template: `index.html`,
		// favicon : "FAVICON_PATH",
		minify  : {
			collapseBooleanAttributes    : true,
			collapseInlineTagWhitespace  : true,
			collapseWhitespace           : true,
			includeAutoGeneratedTags     : false,
			keepClosingSlash             : true,
			minifyCSS                    : true,
			minifyJS                     : true,
			minifyURLs                   : true,
			removeAttributeQuotes        : true,
			removeComments               : true,
			removeEmptyAttributes        : true,
			removeRedundantAttributes    : true,
			removeScriptTypeAttributes   : true,
			removeStyleLinkTypeAttributes: true,
			removeTagWhitespace          : true,
			useShortDoctype              : true,
		}
	}),
	(new webpack.HotModuleReplacementPlugin),// When using hot-reload, the CleanWebpackPlugin and devServer.lazy cannot turn on.
	// New CleanWebpackPlugin(),
	// todo: @note Separating CSS files out from JS files into individuals.
	new MiniCssExtractPlugin({
		filename   : "css/[name].[contenthash:8].css",
		ignoreOrder: true,
	}),
];

const _module = {
	rules: [
		// {
		// 	Test: /\.jsx?$/,
		// 	Exclude: /node_modules/,
		// 	Include: [
		// 		Path.resolve("src")
		// 	],
		// 	Use: [{
		// 		Loader: 'babel-loader',
		// 		/**
		// * @Note this configuration is react
		// * */
		// 		// options: {
		// 		//     presets: ['@babel/preset-react'],
		// 		// }
		// 	}]
		// },
		// {
		// 	Test: /\.vue$/,
		// 	Loader: 'vue-loader',
		// 	Exclude: /node_modules/,
		// 	Include: [
		// 		Path.resolve("src/Vue")
		// 	],
		// },
		/**
   * @Note tpyescript
   * @Steps
   *      1. npm install --save-dev typescript ts-loader
   *      2. create a tsconfig.json
   *      3. insert loader in webpack
   * */
		{
			test   : /\.tsx?$/,
			exclude: /node_modules/,
			include: path.resolve("src"),
			use    : 'ts-loader',
		},
		{
			test   : /\.css$/i,
			exclude: /node_modules/,
			include: path.resolve('src'),
			use    : [
				// MiniCssExtractPlugin.loader,
				'style-loader',
				'css-loader',
			],
		},
		{
			test   : /\.s[ac]ss$/i,
			exclude: /node_modules/,
			include: path.resolve('src'),
			use    : [
				// MiniCssExtractPlugin.loader,
				'style-loader',
				'css-loader',
				'sass-loader',
			],
		},
		{
			test     : /\.(png|jpe?g|gif)$/,
			type     : "asset/resource",
			generator: {
				filename: "img/[name].[contenthash:8].[ext]",
			},
		},
		{
			test     : /\.(woff|woff2|eot|ttf|otf)$/,
			type     : "asset/resource",
			generator: {
				filename: "font/[name].[contenthash:8].[ext]",
			},
		},
		{
			test     : /\.ico$/,
			type     : "asset/resource",
			generator: {
				filename: "ico/[name].[contenthash:8].ico",
			},
		},
	],
};

// https://juejin.im/post/6844903450644316174
// Prod => cheap-module-source-map
// Dev => cheap-module-eval-source-map
const devtool = "cheap-module-source-map";

const performance = {
	hints            : "warning",
	maxEntrypointSize: 1024000,
	maxAssetSize     : 256000,
};

const optimization = {
	usedExports : true,
	runtimeChunk: true,
	splitChunks : {
		chunks                : "async",//async, all,
		minSize               : 0,
		// MinRemainingSize: 0,
		maxSize               : 100000,
		minChunks             : 1,
		maxAsyncRequests      : 30,
		maxInitialRequests    : 30,
		automaticNameDelimiter: ".",
		enforceSizeThreshold  : 50000,
		cacheGroups           : {
			defaultVendors: {
				test    : /node_modules/,
				priority: -10
			},
			commons: {
				chunks   : 'initial',
				name     : 'commons', //分割出來的檔案命名
				minChunks: 2, //被引入2次以上的code就會被提取出來
				priority : 1, //檔案的優先順序，數字越大表示優先級越高
			},
			vendor: {
				test    : /node_modules/, //提取引入的模組
				chunks  : 'initial',
				name    : 'vendor', //分割出來的檔案命名
				priority: 2, //檔案的優先順序，數字越大表示優先級越高
				enforce : true
			}
		}
	},
	minimizer: [ (new CSSMinimizerPlugin), ],
};

const config = {
	// set up as production will auto minify the js files.
	mode  : 'development', // development, production
	module: _module,
	entry,
	output,
	devServer,
	resolve,
	plugins,
	devtool,
	performance,
	optimization
};

module.exports = config;