import {Provider} from "@ethersproject/abstract-provider";
import * as providers from "@ethersproject/providers";

type ContractInterface = {
    id: string,
    decimals: number
    contractAddress: string,
    contractAbi: any[],
    provider: Provider,
    address?: string,
    method?: string,
}

const ContractConfig: ContractInterface[] = ((_provider: Provider) => [
    {
        id: "UniLP_AFI_USDC",
        provider: _provider,
        decimals: 18,
        contractAddress: "0xd40cADE3f71C20Ba6FE940E431c890dC100E97d6",
        contractAbi: [
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"_lpToken",
                        "type":"address"
                    },
                    {
                        "internalType":"address",
                        "name":"_rewardToken",
                        "type":"address"
                    }
                ],
                "stateMutability":"nonpayable",
                "type":"constructor"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"previousOwner",
                        "type":"address"
                    },
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"newOwner",
                        "type":"address"
                    }
                ],
                "name":"OwnershipTransferred",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"RewardAdded",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"RewardPaid",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"Staked",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"Withdrawn",
                "type":"event"
            },
            {
                "inputs":[

                ],
                "name":"DURATION",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"account",
                        "type":"address"
                    }
                ],
                "name":"balanceOf",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"account",
                        "type":"address"
                    }
                ],
                "name":"earned",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"erc20Token",
                "outputs":[
                    {
                        "internalType":"contract IERC20",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"exit",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getData1",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getData2",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getReward",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"isOnlyRewardDistribution",
                "outputs":[
                    {
                        "internalType":"bool",
                        "name":"",
                        "type":"bool"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"isOwner",
                "outputs":[
                    {
                        "internalType":"bool",
                        "name":"",
                        "type":"bool"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lastTimeRewardApplicable",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lastUpdateTime",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lpToken",
                "outputs":[
                    {
                        "internalType":"contract IERC20",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"notifyRewardAmount",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"owner",
                "outputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"periodFinish",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"renounceOwnership",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardDistribution",
                "outputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardPerToken",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardPerTokenStored",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardRate",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "name":"rewards",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"_rewardDistribution",
                        "type":"address"
                    }
                ],
                "name":"setRewardDistribution",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"stake",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"totalSupply",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"newOwner",
                        "type":"address"
                    }
                ],
                "name":"transferOwnership",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "name":"userRewardPerTokenPaid",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"withdraw",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            }
        ],
    },
    {
        id: "AFI Governance",
        provider: _provider,
        decimals: 18,
        contractAddress: "0x9cd43309C9E122A13b466391bABC5deC8bE1E01E",
        contractAbi: [
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"_lpToken",
                        "type":"address"
                    },
                    {
                        "internalType":"address",
                        "name":"_rewardToken",
                        "type":"address"
                    }
                ],
                "stateMutability":"nonpayable",
                "type":"constructor"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"previousOwner",
                        "type":"address"
                    },
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"newOwner",
                        "type":"address"
                    }
                ],
                "name":"OwnershipTransferred",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"RewardAdded",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"RewardPaid",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"Staked",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"Withdrawn",
                "type":"event"
            },
            {
                "inputs":[

                ],
                "name":"DURATION",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"account",
                        "type":"address"
                    }
                ],
                "name":"balanceOf",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"account",
                        "type":"address"
                    }
                ],
                "name":"earned",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"erc20Token",
                "outputs":[
                    {
                        "internalType":"contract IERC20",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"exit",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getData1",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getData2",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getReward",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"isOnlyRewardDistribution",
                "outputs":[
                    {
                        "internalType":"bool",
                        "name":"",
                        "type":"bool"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"isOwner",
                "outputs":[
                    {
                        "internalType":"bool",
                        "name":"",
                        "type":"bool"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lastTimeRewardApplicable",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lastUpdateTime",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lpToken",
                "outputs":[
                    {
                        "internalType":"contract IERC20",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"notifyRewardAmount",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"owner",
                "outputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"periodFinish",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"renounceOwnership",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardDistribution",
                "outputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardPerToken",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardPerTokenStored",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardRate",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "name":"rewards",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"_rewardDistribution",
                        "type":"address"
                    }
                ],
                "name":"setRewardDistribution",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"stake",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"totalSupply",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"newOwner",
                        "type":"address"
                    }
                ],
                "name":"transferOwnership",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "name":"userRewardPerTokenPaid",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"withdraw",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            }
        ],
    },
    {
        id: "afiUSDC",
        provider: _provider,
        decimals: 18,
        contractAddress: "0xAC7DE028cCe2a99e9399aB0bE198Bc950994f50C",
        contractAbi: [
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"_lpToken",
                        "type":"address"
                    },
                    {
                        "internalType":"address",
                        "name":"_rewardToken",
                        "type":"address"
                    }
                ],
                "stateMutability":"nonpayable",
                "type":"constructor"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"previousOwner",
                        "type":"address"
                    },
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"newOwner",
                        "type":"address"
                    }
                ],
                "name":"OwnershipTransferred",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"RewardAdded",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"RewardPaid",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"Staked",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"Withdrawn",
                "type":"event"
            },
            {
                "inputs":[

                ],
                "name":"DURATION",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"account",
                        "type":"address"
                    }
                ],
                "name":"balanceOf",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"account",
                        "type":"address"
                    }
                ],
                "name":"earned",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"erc20Token",
                "outputs":[
                    {
                        "internalType":"contract IERC20",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"exit",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getData1",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getData2",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getReward",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"isOnlyRewardDistribution",
                "outputs":[
                    {
                        "internalType":"bool",
                        "name":"",
                        "type":"bool"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"isOwner",
                "outputs":[
                    {
                        "internalType":"bool",
                        "name":"",
                        "type":"bool"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lastTimeRewardApplicable",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lastUpdateTime",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lpToken",
                "outputs":[
                    {
                        "internalType":"contract IERC20",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"notifyRewardAmount",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"owner",
                "outputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"periodFinish",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"renounceOwnership",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardDistribution",
                "outputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardPerToken",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardPerTokenStored",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardRate",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "name":"rewards",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"_rewardDistribution",
                        "type":"address"
                    }
                ],
                "name":"setRewardDistribution",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"stake",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"totalSupply",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"newOwner",
                        "type":"address"
                    }
                ],
                "name":"transferOwnership",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "name":"userRewardPerTokenPaid",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"withdraw",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            }
        ],
    },
    {
        id: "afiUSDT",
        provider: _provider,
        decimals: 18,
        contractAddress: "0x825241bA78700c11a4615523dF4B70F78C7384aa",
        contractAbi: [
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"_lpToken",
                        "type":"address"
                    },
                    {
                        "internalType":"address",
                        "name":"_rewardToken",
                        "type":"address"
                    }
                ],
                "stateMutability":"nonpayable",
                "type":"constructor"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"previousOwner",
                        "type":"address"
                    },
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"newOwner",
                        "type":"address"
                    }
                ],
                "name":"OwnershipTransferred",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"RewardAdded",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"RewardPaid",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"Staked",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"Withdrawn",
                "type":"event"
            },
            {
                "inputs":[

                ],
                "name":"DURATION",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"account",
                        "type":"address"
                    }
                ],
                "name":"balanceOf",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"account",
                        "type":"address"
                    }
                ],
                "name":"earned",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"erc20Token",
                "outputs":[
                    {
                        "internalType":"contract IERC20",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"exit",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getData1",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getData2",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getReward",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"isOnlyRewardDistribution",
                "outputs":[
                    {
                        "internalType":"bool",
                        "name":"",
                        "type":"bool"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"isOwner",
                "outputs":[
                    {
                        "internalType":"bool",
                        "name":"",
                        "type":"bool"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lastTimeRewardApplicable",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lastUpdateTime",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lpToken",
                "outputs":[
                    {
                        "internalType":"contract IERC20",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"notifyRewardAmount",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"owner",
                "outputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"periodFinish",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"renounceOwnership",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardDistribution",
                "outputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardPerToken",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardPerTokenStored",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardRate",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "name":"rewards",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"_rewardDistribution",
                        "type":"address"
                    }
                ],
                "name":"setRewardDistribution",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"stake",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"totalSupply",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"newOwner",
                        "type":"address"
                    }
                ],
                "name":"transferOwnership",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "name":"userRewardPerTokenPaid",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"withdraw",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            }
        ],
    },
    {
        id: "afiDAI",
        provider: _provider,
        decimals: 18,
        contractAddress: "0x8667D16150AcAA1FF19AcC5E5c64Bf0Ba1d551b3",
        contractAbi: [
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"_lpToken",
                        "type":"address"
                    },
                    {
                        "internalType":"address",
                        "name":"_rewardToken",
                        "type":"address"
                    }
                ],
                "stateMutability":"nonpayable",
                "type":"constructor"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"previousOwner",
                        "type":"address"
                    },
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"newOwner",
                        "type":"address"
                    }
                ],
                "name":"OwnershipTransferred",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"RewardAdded",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"RewardPaid",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"Staked",
                "type":"event"
            },
            {
                "anonymous":false,
                "inputs":[
                    {
                        "indexed":true,
                        "internalType":"address",
                        "name":"user",
                        "type":"address"
                    },
                    {
                        "indexed":false,
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"Withdrawn",
                "type":"event"
            },
            {
                "inputs":[

                ],
                "name":"DURATION",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"account",
                        "type":"address"
                    }
                ],
                "name":"balanceOf",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"account",
                        "type":"address"
                    }
                ],
                "name":"earned",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"erc20Token",
                "outputs":[
                    {
                        "internalType":"contract IERC20",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"exit",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getData1",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getData2",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"getReward",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"isOnlyRewardDistribution",
                "outputs":[
                    {
                        "internalType":"bool",
                        "name":"",
                        "type":"bool"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"isOwner",
                "outputs":[
                    {
                        "internalType":"bool",
                        "name":"",
                        "type":"bool"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lastTimeRewardApplicable",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lastUpdateTime",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"lpToken",
                "outputs":[
                    {
                        "internalType":"contract IERC20",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"reward",
                        "type":"uint256"
                    }
                ],
                "name":"notifyRewardAmount",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"owner",
                "outputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"periodFinish",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"renounceOwnership",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardDistribution",
                "outputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardPerToken",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardPerTokenStored",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"rewardRate",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "name":"rewards",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"_rewardDistribution",
                        "type":"address"
                    }
                ],
                "name":"setRewardDistribution",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"stake",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[

                ],
                "name":"totalSupply",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"newOwner",
                        "type":"address"
                    }
                ],
                "name":"transferOwnership",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"address",
                        "name":"",
                        "type":"address"
                    }
                ],
                "name":"userRewardPerTokenPaid",
                "outputs":[
                    {
                        "internalType":"uint256",
                        "name":"",
                        "type":"uint256"
                    }
                ],
                "stateMutability":"view",
                "type":"function"
            },
            {
                "inputs":[
                    {
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    }
                ],
                "name":"withdraw",
                "outputs":[

                ],
                "stateMutability":"nonpayable",
                "type":"function"
            }
        ],
    }
])(new providers.JsonRpcProvider(process.env.RPC_URL))

export { ContractInterface, ContractConfig }